#!/bin/bash
./PFPOffset -f ../data/variable_test_data/BendTube_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/BendTube_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/CoverSlipCleaningHolder2b_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/CoverSlipCleaningHolder2b_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/Hub_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/Hub_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/LowerControlArm_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/LowerControlArm_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/anti_backlash_nut_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/anti_backlash_nut_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/asm007_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/asm007_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bamboo_pen_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bamboo_pen_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bearing_plate_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bearing_plate_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/beveled_shoulder_1_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/beveled_shoulder_1_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/beveled_shoulder_2_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/beveled_shoulder_2_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/blade_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/blade_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bladefem_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bladefem_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/blockLP_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/blockLP_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bolt_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bolt_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bone1_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bone1_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bone_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bone_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bozbezbozzel50K_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bozbezbozzel50K_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/buddha_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/buddha_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/bunny_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/bunny_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/cad5-tri_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/cad5-tri_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/carter30k-mod_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/carter30k-mod_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/casting2_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/casting2_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/casting_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/casting_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/cow2_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/cow2_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/cube_minus_sphere_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/cube_minus_sphere_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/cup-tri_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/cup-tri_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/deckel_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/deckel_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/delta_arm2_remesh_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/delta_arm2_remesh_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/des6_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/des6_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/des7_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/des7_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/eros100K_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/eros100K_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/fandisk_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/fandisk_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/fertility_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/fertility_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/gps_25_cut_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/gps_25_cut_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/greek_sculpture_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/greek_sculpture_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/gyroidpuzzle_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/gyroidpuzzle_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/halved_oblique_scarf_2_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/halved_oblique_scarf_2_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/halved_oblique_scarf_3_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/halved_oblique_scarf_3_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/hinge_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/hinge_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/impeller_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/impeller_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/inlay_dovetail_3_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/inlay_dovetail_3_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/lego_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/lego_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/lion_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/lion_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/lock_Lp_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/lock_Lp_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/magalie_hand100K_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/magalie_hand100K_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/mech_piece_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/mech_piece_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/mid2Fem_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/mid2Fem_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/motor_tail_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/motor_tail_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/nasty_cheese_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/nasty_cheese_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/nugear_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/nugear_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/octa_flower_Lp_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/octa_flower_Lp_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/part20k_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/part20k_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/part2_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/part2_offset.obj2  -i=2 -t=10
./PFPOffset -f ../data/variable_test_data/pinion_offset.obj2  -i=1 -t=10
./PFPOffset -f ../data/variable_test_data/pinion_offset.obj2  -i=2 -t=10